version: '2'
services:
  web:
    build:
      context: .
      dockerfile: resources/docker/web.Dockerfile
      args:
        - HOST_USER_ID
    ports:
      - '8080:80'
    depends_on:
      - db
    volumes:
      - ./data/www:/www
      - ./src:/www/racktables/wwwroot/racknews
  db:
    build:
      context: .
      dockerfile: resources/docker/db.Dockerfile
      args:
        - HOST_USER_ID
    environment:
      MYSQL_ROOT_PASSWORD: 'secretlol'
    volumes:
      - ./data/mysql:/var/lib/mysql
